### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by uvchik**
I think we should increase the test coverage besides the examples. We can add tests step by step.

### CODE REVIEW

**Comment by uvchik** [comment]
We should add a CI for the tests. 

@oemof/demandlib If you agree I could add the template of solph, feedinlib, network... with the github integration tests.

**Comment by p-snft** [comment]
> We should add a CI for the tests.
> 
> @oemof/demandlib If you agree I could add the template of solph, feedinlib, network... with the github integration tests.

Thanks for the suggestion. I totally agree. So, would you do this?

**Comment by uvchik** [comment]
Yes, as soon as I will find some time.

**Comment by uvchik** [comment]
I will merge it into the revision branch to avoid merge conflicts.

**Pull request merged**
