### PR TITLE
Features/improve package setup

### PR DESCRIPTION
**Pull request by gplssm**
Contains improvements regarding data files contained in the pip package and locations when installed via pip.

### CODE REVIEW

**Comment by gplssm** [comment]
We should discuss if we want to have console scripts for examples of the demandlib. To reduce number of scripts being installed we could implement some simple arg parsing to achieve somthing like

```
demandlib --examples power
```
or similar.

**Comment by uvchik** [comment]
Thank you for your initiative to make the examples accessible after a pip install.

I really like the idea of executing the example in that way, but do you think it will work for Windows users?

**Comment by gplssm** [comment]
As far as I know, this should work platform independent. @ludee could you test this for us? Just download latest [demandlib](https://github.com/oemof/demandlib/tree/48e14e2f5cb6d7be0e9ec2f39858002b41911245) and checkout the branch `features/improve-package-setup`. Afterwards install demandlib from local sources by

```
pip3 install <path-to-sources-of-demandlib>
```
(or similar adapted to anaconda)

and run the example script by executing
```
demandlib_heat_example[.exe]
```
in a command-line.

@uvchik do you think it's worth to use one script for both example differentiating via function arguments?

**Comment by uvchik** [comment]
All variants are fine for me:
```
demandlib_example_heat
demandlib_example heat
demandlib_example --heat
```

With the second and the third variant we would be able to run both examples using `demandlib_example all` or without parameter.

I would use the variant, that is less work :exclamation:

**Comment by gplssm** [comment]
Fine! Then decision is made that we have to scripts. Each for an example as currently implemented here.

**Pull request merged**
